# actでの実行コマンド `act workflow_dispatch -j Execute-Top-Level-Action --secret-file .secrets --container-architecture linux/amd64`
name: Execute Top Level Action
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
jobs:
  Execute-Top-Level-Action:
    if: ${{ (github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }} # secretsはワークフローからしか読みだせず、カスタムアクションから読み出せないので注意